### ISSUE TITLE
Levantar possíveis keynote speakers do iFood.

### ISSUE THREAD

**Issue by ghostproducer** [sprt-michelle/devopsdaysvix#12]
Um dos profissionais da equipe enviou a proposta para o PaperCall.

**Comment by jaksongaleti** [comment]
O Eduardo Ximenes já submeteu a proposta de palestra com o tema:

Title: DevOps e SRE, onde essas forças se cruzam

Description:

A proposta desta palestra é apresentar como tratamos, faz um bom tempo, a entrega de infraestrutura self-service para que os times de desenvolvimento possam criar, modificar, utilizar e gerenciar os recursos disponíveis em nossa estrutura.

Além disso, apresentarei a jornada de transformação que o time de infraestrutura sofreu até virar SRE, assim como alguns KPI's que nos ajudam na tomada de decisão para realizarmos mudanças visando dar agilidade no dia a dia de ambos os times (DevOps).

Abordarei temas como cultura DevOps, infra as a code, KPIs, chaos engineering, pipeline, SLO, Toil, entre outros.

Details can be found at: https://www.papercall.io/cfps/2633/submissions/97809?xauth=488bcd717d66b0321bbf761cab0f3d6a
