### ISSUE TITLE
Levantar estimativas de custo de realização do evento no Grand Hall (perto da Emescan)

### ISSUE THREAD

**Issue by ghostproducer** [sprt-michelle/devopsdaysvix#18]

**Comment by jaksongaleti** [comment]
[08 DE FEVEREIRO DE 2020 - 200 PESSOAS JAKSON.pdf](https://github.com/sprt-michelle/devopsdaysvix/files/3763793/08.DE.FEVEREIRO.DE.2020.-.200.PESSOAS.JAKSON.pdf)

**Comment by sprt-rafaella** [comment]
[Orçamento - Vitória Grand Hall.pdf](https://github.com/sprt-michelle/devopsdaysvix/files/3824565/Orcamento.-.Vitoria.Grand.Hall.pdf)

Orçamento no Vitória Grand Hall, para 200 pessoas no dia 08/20/2019 - Valor: R$ 4.500,00
