### ISSUE TITLE
Buscar referências de fotógrafo e videomaker.

### ISSUE THREAD

**Issue by ghostproducer** [sprt-michelle/devopsdaysvix#2]

**Comment by ghostproducer** [comment]
Conversei com um conhecido, Fábio Martins, ele disse que faz a cobertura fotográfica (sem vídeo) do evento durante todo o dia por 500 reais. 

Referencia do trabalho dele: https://www.instagram.com/digilabvix/

**Comment by michelleribeiro** [comment]
Jackson (fotográfo da Tribuna): [17:17, 23/10/2019] Jackson - Fotógrafo: Só a cobertura fotográfica fica em 600,00 e disponibilizo algumas imagens para vc ir alimentando as redes sociais.
[17:30, 23/10/2019] Jackson - Fotógrafo: Período de 8 hrs.

**Comment by michelleribeiro** [comment]
@sprt-rafaella Lembrar de cobrar a Straya! :D

**Comment by sprt-rafaella** [comment]
Orçamento do Fotógrafo Guilherme:
R$ 1.600,00 - 8 horas de trabalho, com dois fotógrafos cobrindo o evento.
